// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_Wr5YxemqlMOwsYqy1RrT1Uj9V5qC9g',
    appId: '1:529357508994:web:601170175dace172c47f9b',
    messagingSenderId: '529357508994',
    projectId: 'schoolattendance-f892c',
    authDomain: 'schoolattendance-f892c.firebaseapp.com',
    storageBucket: 'schoolattendance-f892c.firebasestorage.app',
    measurementId: 'G-LH41ZQVV7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo8vVYB0ZLcx8W_Wg-4v5_W2Bli_mq9WQ',
    appId: '1:529357508994:android:4578b2e5742b57bac47f9b',
    messagingSenderId: '529357508994',
    projectId: 'schoolattendance-f892c',
    storageBucket: 'schoolattendance-f892c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxieLWtFjUOpNjNr4xzTuqlV3uHnz6c_0',
    appId: '1:529357508994:ios:b6ca4d538f4d7fd7c47f9b',
    messagingSenderId: '529357508994',
    projectId: 'schoolattendance-f892c',
    storageBucket: 'schoolattendance-f892c.firebasestorage.app',
    iosBundleId: 'com.example.attendancePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs_Wr5YxemqlMOwsYqy1RrT1Uj9V5qC9g',
    appId: '1:529357508994:web:f29f8f942cd4d4e9c47f9b',
    messagingSenderId: '529357508994',
    projectId: 'schoolattendance-f892c',
    authDomain: 'schoolattendance-f892c.firebaseapp.com',
    storageBucket: 'schoolattendance-f892c.firebasestorage.app',
    measurementId: 'G-YFYJT2SD0E',
  );

}